DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS QUESTION;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS QUESTION_CATEGORY;
DROP TABLE IF EXISTS ANSWER;

CREATE TABLE USERS (
       ID INT NOT NULL AUTO_INCREMENT
     , USERNAME VARCHAR(500) NOT NULL
     , PSW VARCHAR(500)
     , EMAIL VARCHAR(500) NOT NULL
     , PICTURE BLOB
     , PRIMARY KEY (ID)
);
CREATE TABLE QUESTION (
       ID INT NOT NULL AUTO_INCREMENT
     , USERS_ID INT NOT NULL
     , TITLE VARCHAR(500) NOT NULL
     , BODY VARCHAR(2000) NOT NULL
     , CREATE_DATE DATE
     , PRIMARY KEY (ID)
     , CONSTRAINT FK_QUESTION_USERS FOREIGN KEY (USERS_ID) REFERENCES USERS (ID)
);

CREATE TABLE CATEGORY (
       ID INT NOT NULL AUTO_INCREMENT
     , NAME VARCHAR(500) NOT NULL
     , PRIMARY KEY (ID)
);

CREATE TABLE QUESTION_CATEGORY (
       QUESTION_ID INT NOT NULL
     , CATEGORY_ID INT NOT NULL
     , PRIMARY KEY (QUESTION_ID, CATEGORY_ID)
     , CONSTRAINT FK_QUESTION_CATEGORY_1 FOREIGN KEY (QUESTION_ID)
                  REFERENCES QUESTION (ID) ON DELETE CASCADE
     , CONSTRAINT FK_QUESTION_CATEGORY_2 FOREIGN KEY (CATEGORY_ID)
                  REFERENCES CATEGORY (ID) ON DELETE CASCADE
);

CREATE TABLE ANSWER (
       ID INT NOT NULL AUTO_INCREMENT
     , QUESTION_ID INT NOT NULL
     , USERS_ID INT NOT NULL
     , BODY VARCHAR(2000) NOT NULL
     , CREATE_DATE DATE
     , PRIMARY KEY (ID)
     , CONSTRAINT FK_ANSWER_QUESTION FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION (ID)
     , CONSTRAINT FK_ANSWER_USERS FOREIGN KEY (USERS_ID) REFERENCES USERS (ID)
);